baseURL = "http://example.org/"
languageCode = "es"
title = "My Web"
theme = "harbor"


   [Author]
      name = "Hugo Bugjay"

  [[params.nav]]
     identifier = "contacto"
     name = "contacto"
     icon = "fas fa-user fa-lg"
     url = "/contacto/"
     weight = 3

 [[params.nav]]
     identifier = "Posts"
     name = "posts"
     icon = "fas fa-tag fa-lg"
     url = "posts"
     weight = 3
  [[params.nav]]
      identifier = "search"
      name = "Search"
      icon = "fas fa-search fa-lg "
      url = "search"
      weight = 3
 
  [[params.github]]
     name = "github"
     url = "https://github.com/RootJayne"
     icon = "fas fa-brands fa-github-square fa-lg "
     alt = "github"
     



   [params.logo]
      url = "pngwing.com.png" # static/images/icon.png
      width = 75
     height = 75
      alt = "Logo"

 